import AppBar from "@/components/appbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-full h-screen bg-white flex flex-col container mx-auto px-4 `}
      >
        <AppBar />
        <div className="flex-grow">{children}</div>
      </body>
    </html>
  );
}
